language: node_js
node_js:
  - "8"
before_install:
  - npm install -g yarn --cache-min 999999999
install:
  - yarn
cache:
  directories:
    - "node_modules"
script:
  - yarn test
after_success:
  - yarn run report-coverage