language: node_js
node_js:
  - "8"
install:
  - yarn
cache:
  directories:
    - "node_modules"
script:
  - yarn test
  - yarn danger
after_success:
  - yarn run report-coverage
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      yarn run semantic-release;
    fi'